"""empty message

Revision ID: d4430e897553
Revises: 
Create Date: 2026-01-21 12:48:22.242062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4430e897553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_post_parent_id', 'post', ['parent_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_question_category'))
        batch_op.create_index(batch_op.f('ix_question_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_type'), ['type'], unique=False)
        batch_op.create_foreign_key('fk_question_owner_id', 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))

    with op.batch_alter_table('workshop_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_draft_work_id', 'workshop_work', ['work_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop_draft', schema=None) as batch_op:
        batch_op.drop_constraint('fk_draft_work_id', type_='foreignkey')
        batch_op.drop_column('work_id')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('mode')

    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.drop_column('mode')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_owner_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_question_type'))
        batch_op.drop_index(batch_op.f('ix_question_owner_id'))
        batch_op.create_index(batch_op.f('idx_question_category'), ['category'], unique=False)
        batch_op.drop_column('owner_id')
        batch_op.drop_column('type')
        batch_op.drop_column('mode')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_parent_id', type_='foreignkey')
        batch_op.drop_column('mode')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
